# Created by: PyQt6 UI code generator 6.4.2
# pyuic6 -x filename.ui -o filename.py

from PyQt6 import QtCore, QtGui, QtWidgets
from matplotlib.backends.backend_qtagg import FigureCanvasQTAgg as FigureCanvas #used to embed matplotlib figure into a Widget
from matplotlib.figure import Figure 
        
class mainUi(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1270, 850)
        MainWindow.setMinimumSize(QtCore.QSize(1270, 850))
        MainWindow.setMaximumSize(QtCore.QSize(1270, 850))
        MainWindow.setStatusTip("")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.line_8 = QtWidgets.QFrame(parent=self.centralwidget)
        self.line_8.setGeometry(QtCore.QRect(1040, 175, 16, 600))
        self.line_8.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_8.setObjectName("line_8")
        self.line_7 = QtWidgets.QFrame(parent=self.centralwidget)
        self.line_7.setGeometry(QtCore.QRect(11, 160, 1250, 16))
        self.line_7.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_7.setObjectName("line_7")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 10, 1250, 150))
        self.widget.setMinimumSize(QtCore.QSize(1250, 150))
        self.widget.setMaximumSize(QtCore.QSize(1250, 150))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget1 = QtWidgets.QWidget(parent=self.widget)
        self.widget1.setMinimumSize(QtCore.QSize(500, 150))
        self.widget1.setMaximumSize(QtCore.QSize(500, 150))
        self.widget1.setObjectName("widget1")
        self.gridLayout = QtWidgets.QGridLayout(self.widget1)
        self.gridLayout.setObjectName("gridLayout")
        self.labelSTIS = QtWidgets.QLabel(parent=self.widget1)
        self.labelSTIS.setMinimumSize(QtCore.QSize(375, 0))
        self.labelSTIS.setMaximumSize(QtCore.QSize(375, 50))
        self.labelSTIS.setObjectName("labelSTIS")
        self.gridLayout.addWidget(self.labelSTIS, 1, 0, 1, 1)
        self.openSTIS = QtWidgets.QPushButton(parent=self.widget1)
        self.openSTIS.setMaximumSize(QtCore.QSize(100, 25))
        self.openSTIS.setObjectName("openSTIS")
        self.gridLayout.addWidget(self.openSTIS, 1, 1, 1, 1)
        self.openCOS = QtWidgets.QPushButton(parent=self.widget1)
        self.openCOS.setMaximumSize(QtCore.QSize(100, 25))
        self.openCOS.setObjectName("openCOS")
        self.gridLayout.addWidget(self.openCOS, 0, 1, 1, 1)
        self.starInput = QtWidgets.QLineEdit(parent=self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.starInput.sizePolicy().hasHeightForWidth())
        self.starInput.setSizePolicy(sizePolicy)
        self.starInput.setMinimumSize(QtCore.QSize(100, 18))
        self.starInput.setMaximumSize(QtCore.QSize(100, 25))
        self.starInput.setObjectName("starInput")
        self.gridLayout.addWidget(self.starInput, 2, 1, 1, 1)
        self.starName = QtWidgets.QLabel(parent=self.widget1)
        self.starName.setMinimumSize(QtCore.QSize(100, 18))
        self.starName.setMaximumSize(QtCore.QSize(75, 50))
        self.starName.setObjectName("starName")
        self.gridLayout.addWidget(self.starName, 2, 0, 1, 1)
        self.labelCOS = QtWidgets.QLabel(parent=self.widget1)
        self.labelCOS.setMinimumSize(QtCore.QSize(375, 0))
        self.labelCOS.setMaximumSize(QtCore.QSize(375, 50))
        self.labelCOS.setToolTip("")
        self.labelCOS.setWhatsThis("")
        self.labelCOS.setObjectName("labelCOS")
        self.gridLayout.addWidget(self.labelCOS, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.widget1)
        self.line_6 = QtWidgets.QFrame(parent=self.widget)
        self.line_6.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_6.setObjectName("line_6")
        self.horizontalLayout.addWidget(self.line_6)
        self.widget2 = QtWidgets.QWidget(parent=self.widget)
        self.widget2.setMinimumSize(QtCore.QSize(150, 150))
        self.widget2.setMaximumSize(QtCore.QSize(150, 150))
        self.widget2.setObjectName("widget2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lifeLabel = QtWidgets.QLabel(parent=self.widget2)
        self.lifeLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.lifeLabel.setMaximumSize(QtCore.QSize(150, 37))
        self.lifeLabel.setObjectName("lifeLabel")
        self.verticalLayout_3.addWidget(self.lifeLabel)
        self.cen1327Label = QtWidgets.QLabel(parent=self.widget2)
        self.cen1327Label.setMinimumSize(QtCore.QSize(0, 0))
        self.cen1327Label.setMaximumSize(QtCore.QSize(150, 38))
        self.cen1327Label.setObjectName("cen1327Label")
        self.verticalLayout_3.addWidget(self.cen1327Label)
        self.spectypeLabel = QtWidgets.QLabel(parent=self.widget2)
        self.spectypeLabel.setMaximumSize(QtCore.QSize(150, 37))
        self.spectypeLabel.setObjectName("spectypeLabel")
        self.verticalLayout_3.addWidget(self.spectypeLabel)
        self.sideLabel = QtWidgets.QLabel(parent=self.widget2)
        self.sideLabel.setMaximumSize(QtCore.QSize(150, 38))
        self.sideLabel.setObjectName("sideLabel")
        self.verticalLayout_3.addWidget(self.sideLabel)
        self.horizontalLayout.addWidget(self.widget2)
        self.line_4 = QtWidgets.QFrame(parent=self.widget)
        self.line_4.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout.addWidget(self.line_4)
        self.widget3 = QtWidgets.QWidget(parent=self.widget)
        self.widget3.setMinimumSize(QtCore.QSize(90, 150))
        self.widget3.setMaximumSize(QtCore.QSize(90, 150))
        self.widget3.setObjectName("widget3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget3)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.whichLine = QtWidgets.QLabel(parent=self.widget3)
        self.whichLine.setMinimumSize(QtCore.QSize(0, 24))
        self.whichLine.setMaximumSize(QtCore.QSize(90, 20))
        self.whichLine.setObjectName("whichLine")
        self.verticalLayout_6.addWidget(self.whichLine)
        self.radioLyA = QtWidgets.QRadioButton(parent=self.widget3)
        self.radioLyA.setMaximumSize(QtCore.QSize(100, 20))
        self.radioLyA.setObjectName("radioLyA")
        self.groupLine = QtWidgets.QButtonGroup(MainWindow)
        self.groupLine.setObjectName("groupLine")
        self.groupLine.addButton(self.radioLyA)
        self.verticalLayout_6.addWidget(self.radioLyA)
        self.radioOI2 = QtWidgets.QRadioButton(parent=self.widget3)
        self.radioOI2.setMaximumSize(QtCore.QSize(90, 20))
        self.radioOI2.setObjectName("radioOI2")
        self.groupLine.addButton(self.radioOI2)
        self.verticalLayout_6.addWidget(self.radioOI2)
        self.radioOI5 = QtWidgets.QRadioButton(parent=self.widget3)
        self.radioOI5.setMaximumSize(QtCore.QSize(90, 20))
        self.radioOI5.setObjectName("radioOI5")
        self.groupLine.addButton(self.radioOI5)
        self.verticalLayout_6.addWidget(self.radioOI5)
        self.radioOI6 = QtWidgets.QRadioButton(parent=self.widget3)
        self.radioOI6.setMaximumSize(QtCore.QSize(90, 20))
        self.radioOI6.setObjectName("radioOI6")
        self.groupLine.addButton(self.radioOI6)
        self.verticalLayout_6.addWidget(self.radioOI6)
        self.horizontalLayout.addWidget(self.widget3)
        self.line_5 = QtWidgets.QFrame(parent=self.widget)
        self.line_5.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_5.setObjectName("line_5")
        self.horizontalLayout.addWidget(self.line_5)
        self.widget4 = QtWidgets.QWidget(parent=self.widget)
        self.widget4.setMinimumSize(QtCore.QSize(240, 150))
        self.widget4.setMaximumSize(QtCore.QSize(240, 150))
        self.widget4.setObjectName("widget4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget4)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.editRanges = QtWidgets.QPushButton(parent=self.widget4)
        self.editRanges.setMinimumSize(QtCore.QSize(225, 0))
        self.editRanges.setMaximumSize(QtCore.QSize(225, 25))
        self.editRanges.setObjectName("editRanges")
        self.verticalLayout_5.addWidget(self.editRanges)
        self.labelLyA = QtWidgets.QLabel(parent=self.widget4)
        self.labelLyA.setMaximumSize(QtCore.QSize(240, 20))
        self.labelLyA.setObjectName("labelLyA")
        self.verticalLayout_5.addWidget(self.labelLyA)
        self.labelOI2 = QtWidgets.QLabel(parent=self.widget4)
        self.labelOI2.setMaximumSize(QtCore.QSize(240, 20))
        self.labelOI2.setObjectName("labelOI2")
        self.verticalLayout_5.addWidget(self.labelOI2)
        self.labelOI5 = QtWidgets.QLabel(parent=self.widget4)
        self.labelOI5.setMaximumSize(QtCore.QSize(240, 20))
        self.labelOI5.setObjectName("labelOI5")
        self.verticalLayout_5.addWidget(self.labelOI5)
        self.labelOI6 = QtWidgets.QLabel(parent=self.widget4)
        self.labelOI6.setMaximumSize(QtCore.QSize(240, 20))
        self.labelOI6.setObjectName("labelOI6")
        self.verticalLayout_5.addWidget(self.labelOI6)
        self.horizontalLayout.addWidget(self.widget4)
        self.line_3 = QtWidgets.QFrame(parent=self.widget)
        self.line_3.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout.addWidget(self.line_3)
        self.widget5 = QtWidgets.QWidget(parent=self.widget)
        self.widget5.setMinimumSize(QtCore.QSize(175, 150))
        self.widget5.setMaximumSize(QtCore.QSize(175, 150))
        self.widget5.setObjectName("widget5")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.widget5)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.modeSTIS = QtWidgets.QLabel(parent=self.widget5)
        self.modeSTIS.setMinimumSize(QtCore.QSize(0, 0))
        self.modeSTIS.setMaximumSize(QtCore.QSize(175, 55))
        self.modeSTIS.setObjectName("modeSTIS")
        self.verticalLayout_16.addWidget(self.modeSTIS)
        self.checkSTIS = QtWidgets.QPushButton(parent=self.widget5)
        self.checkSTIS.setMaximumSize(QtCore.QSize(175, 25))
        self.checkSTIS.setObjectName("checkSTIS")
        self.verticalLayout_16.addWidget(self.checkSTIS)
        self.clearSTIS = QtWidgets.QPushButton(parent=self.widget5)
        self.clearSTIS.setMaximumSize(QtCore.QSize(175, 25))
        self.clearSTIS.setObjectName("clearSTIS")
        self.verticalLayout_16.addWidget(self.clearSTIS)
        self.horizontalLayout.addWidget(self.widget5)
        self.widget6 = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget6.setGeometry(QtCore.QRect(12, 180, 1025, 75))
        self.widget6.setMaximumSize(QtCore.QSize(16777215, 75))
        self.widget6.setObjectName("widget6")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.widget6)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.airShift = QtWidgets.QSlider(parent=self.widget6)
        self.airShift.setMinimum(-1500)
        self.airShift.setMaximum(1500)
        self.airShift.setSingleStep(0)
        self.airShift.setPageStep(0)
        self.airShift.setProperty("value", 0)
        self.airShift.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.airShift.setObjectName("airShift")
        self.verticalLayout_7.addWidget(self.airShift)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem1)
        self.shiftLabel = QtWidgets.QLabel(parent=self.widget6)
        self.shiftLabel.setMinimumSize(QtCore.QSize(100, 0))
        self.shiftLabel.setMaximumSize(QtCore.QSize(75, 32))
        self.shiftLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.shiftLabel.setObjectName("shiftLabel")
        self.horizontalLayout_12.addWidget(self.shiftLabel)
        self.shiftInput = QtWidgets.QLineEdit(parent=self.widget6)
        self.shiftInput.setMaximumSize(QtCore.QSize(75, 20))
        self.shiftInput.setWhatsThis("")
        self.shiftInput.setObjectName("shiftInput")
        self.horizontalLayout_12.addWidget(self.shiftInput)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem3)
        self.verticalLayout_7.addLayout(self.horizontalLayout_12)
        self.widget7 = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget7.setGeometry(QtCore.QRect(12, 710, 1025, 75))
        self.widget7.setMaximumSize(QtCore.QSize(16777215, 75))
        self.widget7.setObjectName("widget7")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.widget7)
        self.verticalLayout_21.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem4)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem5)
        self.fitshiftLabel = QtWidgets.QLabel(parent=self.widget7)
        self.fitshiftLabel.setMinimumSize(QtCore.QSize(100, 0))
        self.fitshiftLabel.setMaximumSize(QtCore.QSize(75, 32))
        self.fitshiftLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.fitshiftLabel.setObjectName("fitshiftLabel")
        self.horizontalLayout_23.addWidget(self.fitshiftLabel)
        self.fitshiftInput = QtWidgets.QLineEdit(parent=self.widget7)
        self.fitshiftInput.setMaximumSize(QtCore.QSize(75, 20))
        self.fitshiftInput.setObjectName("fitshiftInput")
        self.horizontalLayout_23.addWidget(self.fitshiftInput)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem6)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem7)
        self.verticalLayout_21.addLayout(self.horizontalLayout_23)
        self.fitShift = QtWidgets.QSlider(parent=self.widget7)
        self.fitShift.setMinimum(-1500)
        self.fitShift.setMaximum(1500)
        self.fitShift.setSingleStep(0)
        self.fitShift.setPageStep(0)
        self.fitShift.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.fitShift.setObjectName("fitShift")
        self.verticalLayout_21.addWidget(self.fitShift)
        self.widget8 = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget8.setGeometry(QtCore.QRect(1061, 180, 200, 580))
        self.widget8.setMaximumSize(QtCore.QSize(200, 16777215))
        self.widget8.setObjectName("widget8")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget8)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem8)
        self.vradLabel = QtWidgets.QLabel(parent=self.widget8)
        self.vradLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.vradLabel.setMaximumSize(QtCore.QSize(200, 35))
        self.vradLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.vradLabel.setObjectName("vradLabel")
        self.verticalLayout.addWidget(self.vradLabel)
        self.vradInput = QtWidgets.QLineEdit(parent=self.widget8)
        self.vradInput.setMinimumSize(QtCore.QSize(0, 0))
        self.vradInput.setMaximumSize(QtCore.QSize(200, 20))
        self.vradInput.setObjectName("vradInput")
        self.verticalLayout.addWidget(self.vradInput)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.vismLabel = QtWidgets.QLabel(parent=self.widget8)
        self.vismLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.vismLabel.setMaximumSize(QtCore.QSize(200, 35))
        self.vismLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.vismLabel.setObjectName("vismLabel")
        self.verticalLayout_4.addWidget(self.vismLabel)
        self.vismInput = QtWidgets.QLineEdit(parent=self.widget8)
        self.vismInput.setMaximumSize(QtCore.QSize(200, 20))
        self.vismInput.setObjectName("vismInput")
        self.verticalLayout_4.addWidget(self.vismInput)
        self.verticalLayout_2.addLayout(self.verticalLayout_4)
        self.line = QtWidgets.QFrame(parent=self.widget8)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.selectLabel = QtWidgets.QLabel(parent=self.widget8)
        self.selectLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.selectLabel.setMaximumSize(QtCore.QSize(100, 20))
        self.selectLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.selectLabel.setObjectName("selectLabel")
        self.verticalLayout_8.addWidget(self.selectLabel)
        self.oneFit = QtWidgets.QRadioButton(parent=self.widget8)
        self.oneFit.setMaximumSize(QtCore.QSize(100, 20))
        self.oneFit.setObjectName("oneFit")
        self.groupFit = QtWidgets.QButtonGroup(MainWindow)
        self.groupFit.setObjectName("groupFit")
        self.groupFit.addButton(self.oneFit)
        self.verticalLayout_8.addWidget(self.oneFit)
        self.twoFit = QtWidgets.QRadioButton(parent=self.widget8)
        self.twoFit.setMaximumSize(QtCore.QSize(100, 20))
        self.twoFit.setObjectName("twoFit")
        self.groupFit.addButton(self.twoFit)
        self.verticalLayout_8.addWidget(self.twoFit)
        self.horizontalLayout_8.addLayout(self.verticalLayout_8)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.selectAirtype = QtWidgets.QLabel(parent=self.widget8)
        self.selectAirtype.setMaximumSize(QtCore.QSize(100, 20))
        self.selectAirtype.setObjectName("selectAirtype")
        self.verticalLayout_10.addWidget(self.selectAirtype)
        self.autoAirmode = QtWidgets.QRadioButton(parent=self.widget8)
        self.autoAirmode.setMaximumSize(QtCore.QSize(100, 20))
        self.autoAirmode.setObjectName("autoAirmode")
        self.groupAirtype = QtWidgets.QButtonGroup(MainWindow)
        self.groupAirtype.setObjectName("groupAirtype")
        self.groupAirtype.addButton(self.autoAirmode)
        self.verticalLayout_10.addWidget(self.autoAirmode)
        self.manualAirmode = QtWidgets.QRadioButton(parent=self.widget8)
        self.manualAirmode.setMaximumSize(QtCore.QSize(100, 20))
        self.manualAirmode.setObjectName("manualAirmode")
        self.groupAirtype.addButton(self.manualAirmode)
        self.verticalLayout_10.addWidget(self.manualAirmode)
        self.horizontalLayout_8.addLayout(self.verticalLayout_10)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.line_2 = QtWidgets.QFrame(parent=self.widget8)
        self.line_2.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_2.addWidget(self.line_2)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.fitComponents = QtWidgets.QPushButton(parent=self.widget8)
        self.fitComponents.setMaximumSize(QtCore.QSize(200, 25))
        self.fitComponents.setObjectName("fitComponents")
        self.verticalLayout_11.addWidget(self.fitComponents)
        self.fitResults = QtWidgets.QPushButton(parent=self.widget8)
        self.fitResults.setMaximumSize(QtCore.QSize(200, 25))
        self.fitResults.setObjectName("fitResults")
        self.verticalLayout_11.addWidget(self.fitResults)
        self.openCutoff = QtWidgets.QPushButton(parent=self.widget8)
        self.openCutoff.setMaximumSize(QtCore.QSize(200, 25))
        self.openCutoff.setObjectName("openCutoff")
        self.verticalLayout_11.addWidget(self.openCutoff)
        self.removeAirglow = QtWidgets.QPushButton(parent=self.widget8)
        self.removeAirglow.setMaximumSize(QtCore.QSize(200, 25))
        self.removeAirglow.setObjectName("removeAirglow")
        self.verticalLayout_11.addWidget(self.removeAirglow)
        self.verticalLayout_2.addLayout(self.verticalLayout_11)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem9)
        self.line_11 = QtWidgets.QFrame(parent=self.widget8)
        self.line_11.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_11.setObjectName("line_11")
        self.verticalLayout_2.addWidget(self.line_11)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem10)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.removalPlots = QtWidgets.QPushButton(parent=self.widget8)
        self.removalPlots.setMaximumSize(QtCore.QSize(200, 25))
        self.removalPlots.setObjectName("removalPlots")
        self.verticalLayout_14.addWidget(self.removalPlots)
        self.openBootstrap = QtWidgets.QPushButton(parent=self.widget8)
        self.openBootstrap.setMaximumSize(QtCore.QSize(200, 25))
        self.openBootstrap.setObjectName("openBootstrap")
        self.verticalLayout_14.addWidget(self.openBootstrap)
        self.saveData = QtWidgets.QPushButton(parent=self.widget8)
        self.saveData.setMaximumSize(QtCore.QSize(200, 25))
        self.saveData.setObjectName("saveData")
        self.verticalLayout_14.addWidget(self.saveData)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_14.addItem(spacerItem11)
        self.verticalLayout_2.addLayout(self.verticalLayout_14)
        self.widget9 = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget9.setGeometry(QtCore.QRect(11, 250, 1025, 452))
        self.widget9.setMinimumSize(QtCore.QSize(1025, 0))
        self.widget9.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget9.setObjectName("widget9")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget9)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.fitScale = QtWidgets.QSlider(parent=self.widget9)
        self.fitScale.setMaximum(1000)
        self.fitScale.setSingleStep(0)
        self.fitScale.setPageStep(0)
        self.fitScale.setProperty("value", 100)
        self.fitScale.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.fitScale.setObjectName("fitScale")
        self.horizontalLayout_3.addWidget(self.fitScale)
        self.widget10 = QtWidgets.QWidget(parent=self.widget9)
        self.widget10.setMaximumSize(QtCore.QSize(65, 16777215))
        self.widget10.setObjectName("widget10")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.widget10)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_12.addItem(spacerItem12)
        self.fitscaleLabel = QtWidgets.QLabel(parent=self.widget10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fitscaleLabel.sizePolicy().hasHeightForWidth())
        self.fitscaleLabel.setSizePolicy(sizePolicy)
        self.fitscaleLabel.setMaximumSize(QtCore.QSize(65, 32))
        self.fitscaleLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.fitscaleLabel.setObjectName("fitscaleLabel")
        self.verticalLayout_12.addWidget(self.fitscaleLabel)
        self.fitscaleInput = QtWidgets.QLineEdit(parent=self.widget10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fitscaleInput.sizePolicy().hasHeightForWidth())
        self.fitscaleInput.setSizePolicy(sizePolicy)
        self.fitscaleInput.setMaximumSize(QtCore.QSize(65, 20))
        self.fitscaleInput.setObjectName("fitscaleInput")
        self.verticalLayout_12.addWidget(self.fitscaleInput)
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_12.addItem(spacerItem13)
        self.horizontalLayout_3.addWidget(self.widget10)
        self.MplWidget = MplWidget(parent=self.widget9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MplWidget.sizePolicy().hasHeightForWidth())
        self.MplWidget.setSizePolicy(sizePolicy)
        self.MplWidget.setMinimumSize(QtCore.QSize(800, 450))
        self.MplWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.MplWidget.setWhatsThis("")
        self.MplWidget.setObjectName("MplWidget")
        self.horizontalLayout_3.addWidget(self.MplWidget)
        self.widget11 = QtWidgets.QWidget(parent=self.widget9)
        self.widget11.setMaximumSize(QtCore.QSize(65, 16777215))
        self.widget11.setObjectName("widget11")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.widget11)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        spacerItem14 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_15.addItem(spacerItem14)
        self.scaleLabel = QtWidgets.QLabel(parent=self.widget11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scaleLabel.sizePolicy().hasHeightForWidth())
        self.scaleLabel.setSizePolicy(sizePolicy)
        self.scaleLabel.setMaximumSize(QtCore.QSize(65, 32))
        self.scaleLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.scaleLabel.setObjectName("scaleLabel")
        self.verticalLayout_15.addWidget(self.scaleLabel)
        self.scaleInput = QtWidgets.QLineEdit(parent=self.widget11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scaleInput.sizePolicy().hasHeightForWidth())
        self.scaleInput.setSizePolicy(sizePolicy)
        self.scaleInput.setMaximumSize(QtCore.QSize(65, 20))
        self.scaleInput.setObjectName("scaleInput")
        self.verticalLayout_15.addWidget(self.scaleInput)
        spacerItem15 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_15.addItem(spacerItem15)
        self.horizontalLayout_3.addWidget(self.widget11)
        self.airScale = QtWidgets.QSlider(parent=self.widget9)
        self.airScale.setMaximum(1000)
        self.airScale.setSingleStep(0)
        self.airScale.setPageStep(0)
        self.airScale.setProperty("value", 100)
        self.airScale.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.airScale.setObjectName("airScale")
        self.horizontalLayout_3.addWidget(self.airScale)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1270, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.openCOS, self.openSTIS)
        MainWindow.setTabOrder(self.openSTIS, self.shiftInput)
        MainWindow.setTabOrder(self.shiftInput, self.scaleInput)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Airglow Removal"))
        self.labelSTIS.setStatusTip(_translate("MainWindow", "Filename of STIS E140M/G140M Data"))
        self.labelSTIS.setText(_translate("MainWindow", "STIS E140M/G140M File:"))
        self.openSTIS.setStatusTip(_translate("MainWindow", "Open a supported STIS E140M/G140M data file"))
        self.openSTIS.setText(_translate("MainWindow", "Open STIS File"))
        self.openCOS.setStatusTip(_translate("MainWindow", "Open a supported COS G130M data file"))
        self.openCOS.setText(_translate("MainWindow", "Open COS File"))
        self.starInput.setStatusTip(_translate("MainWindow", "Edit the name of the star here"))
        self.starName.setStatusTip(_translate("MainWindow", "Edit the name of the star by entering it into the box to the right"))
        self.starName.setText(_translate("MainWindow", "Star Name:"))
        self.labelCOS.setStatusTip(_translate("MainWindow", "Filename of COS G130M Data"))
        self.labelCOS.setText(_translate("MainWindow", "COS G130M File:"))
        self.lifeLabel.setStatusTip(_translate("MainWindow", "The lifetime position used when this data was taken"))
        self.lifeLabel.setText(_translate("MainWindow", "Lifetime Position:"))
        self.cen1327Label.setStatusTip(_translate("MainWindow", "True if data used LP3 and Cenwave 1327"))
        self.cen1327Label.setText(_translate("MainWindow", "LP3 1327: "))
        self.spectypeLabel.setStatusTip(_translate("MainWindow", "True if the star is an M Type star"))
        self.spectypeLabel.setText(_translate("MainWindow", "M Type: "))
        self.sideLabel.setStatusTip(_translate("MainWindow", "True if data was taken using only Side A of the COS detector"))
        self.sideLabel.setText(_translate("MainWindow", "Side A Only:"))
        self.whichLine.setStatusTip(_translate("MainWindow", "Select which airglow line to be fit and removed"))
        self.whichLine.setText(_translate("MainWindow", "Which Line:"))
        self.radioLyA.setStatusTip(_translate("MainWindow", "Lyman Alpha (1215.67 Å)"))
        self.radioLyA.setText(_translate("MainWindow", "Lyα"))
        self.radioOI2.setStatusTip(_translate("MainWindow", "OI 1302 (1302.1685 Å)"))
        self.radioOI2.setText(_translate("MainWindow", "OI 1302"))
        self.radioOI5.setStatusTip(_translate("MainWindow", "OI 1305 (1304.8576 Å)"))
        self.radioOI5.setText(_translate("MainWindow", "OI 1305"))
        self.radioOI6.setStatusTip(_translate("MainWindow", "OI 1306 (1306.0286 Å)"))
        self.radioOI6.setText(_translate("MainWindow", "OI 1306"))
        self.editRanges.setStatusTip(_translate("MainWindow", "Edit the wavelength ranges for the fit calculation and plot display"))
        self.editRanges.setText(_translate("MainWindow", "Edit Ranges"))
        self.labelLyA.setStatusTip(_translate("MainWindow", "Wavelength range for Lyman Alpha"))
        self.labelLyA.setText(_translate("MainWindow", "      Lyα Range:"))
        self.labelOI2.setStatusTip(_translate("MainWindow", "Wavelength range for OI 1302"))
        self.labelOI2.setText(_translate("MainWindow", "OI 1302 Range:"))
        self.labelOI5.setStatusTip(_translate("MainWindow", "Wavelength range for OI 1305"))
        self.labelOI5.setText(_translate("MainWindow", "OI 1305 Range: "))
        self.labelOI6.setStatusTip(_translate("MainWindow", "Wavelength range for OI 1306"))
        self.labelOI6.setText(_translate("MainWindow", "OI 1306 Range: "))
        self.modeSTIS.setStatusTip(_translate("MainWindow", "The STIS grating that the data was taken with"))
        self.modeSTIS.setText(_translate("MainWindow", "STIS Mode:                  "))
        self.checkSTIS.setStatusTip(_translate("MainWindow", "Visual comparison between STIS data and the recovered spectrum, generated using the current parameters"))
        self.checkSTIS.setText(_translate("MainWindow", "Check STIS Comparison"))
        self.clearSTIS.setStatusTip(_translate("MainWindow", "Clear the currently loaded STIS data"))
        self.clearSTIS.setText(_translate("MainWindow", "Clear STIS Data"))
        self.airShift.setStatusTip(_translate("MainWindow", "Move the slider to change the airglow shift input value"))
        self.shiftLabel.setStatusTip(_translate("MainWindow", "Input value for the airglow shift"))
        self.shiftLabel.setText(_translate("MainWindow", "Airglow\n"
"Shift (Å)"))
        self.shiftInput.setToolTip(_translate("MainWindow", "Press \'Enter\' when done"))
        self.shiftInput.setStatusTip(_translate("MainWindow", "Input the airglow shift value"))
        self.fitshiftLabel.setStatusTip(_translate("MainWindow", "The best fit can be shifted in the spectral direction"))
        self.fitshiftLabel.setText(_translate("MainWindow", "Best Fit\n"
"Shift (Å)"))
        self.fitshiftInput.setToolTip(_translate("MainWindow", "Press \'Enter\' when done"))
        self.fitshiftInput.setStatusTip(_translate("MainWindow", "Enter the best fit shift value"))
        self.fitShift.setStatusTip(_translate("MainWindow", "Move the slider to shift the entire fit"))
        self.vradLabel.setStatusTip(_translate("MainWindow", "Radial velocity of the star"))
        self.vradLabel.setText(_translate("MainWindow", "Stellar Radial Velocity\n"
" Initial Guess (km/s):"))
        self.vradInput.setToolTip(_translate("MainWindow", "Press \'Enter\' when done"))
        self.vradInput.setStatusTip(_translate("MainWindow", "Enter radial velocity of the star here"))
        self.vismLabel.setStatusTip(_translate("MainWindow", "Radial velocity of the ISM"))
        self.vismLabel.setText(_translate("MainWindow", "ISM Velocity\n"
" Initial Guess (km/s):"))
        self.vismInput.setToolTip(_translate("MainWindow", "Press \'Enter\' when done"))
        self.vismInput.setStatusTip(_translate("MainWindow", "Enter radial velocity of the ISM here"))
        self.selectLabel.setStatusTip(_translate("MainWindow", "Choose between One Part and Two Part Fitting"))
        self.selectLabel.setText(_translate("MainWindow", "Fit Mode"))
        self.oneFit.setStatusTip(_translate("MainWindow", "Simultaneously fit stellar emission, ISM absorption (for Lyα), and airglow components"))
        self.oneFit.setText(_translate("MainWindow", "One Part"))
        self.twoFit.setStatusTip(_translate("MainWindow", "Using result from One Part fitting, simultaneously fit the stellar and ISM (for Lyα) components on the airglow subtracted profile"))
        self.twoFit.setText(_translate("MainWindow", "Two Part"))
        self.selectAirtype.setStatusTip(_translate("MainWindow", "Choose between Automatic and Manual airglow placement"))
        self.selectAirtype.setText(_translate("MainWindow", "Airglow Mode"))
        self.autoAirmode.setStatusTip(_translate("MainWindow", "Airglow is fit automatically by the fitting routine"))
        self.autoAirmode.setText(_translate("MainWindow", "Automatic"))
        self.manualAirmode.setStatusTip(_translate("MainWindow", "Airglow is manually placed, the fitting routine works with this constraint"))
        self.manualAirmode.setText(_translate("MainWindow", "Manual"))
        self.fitComponents.setStatusTip(_translate("MainWindow", "Toggle between display modes for the main plot"))
        self.fitComponents.setText(_translate("MainWindow", "Toggle Fit Components"))
        self.fitResults.setStatusTip(_translate("MainWindow", "View the best fit parameters and useful statistics"))
        self.fitResults.setText(_translate("MainWindow", "View Fit Results"))
        self.openCutoff.setStatusTip(_translate("MainWindow", "View the normalized residuals, and apply a cutoff if necessary"))
        self.openCutoff.setText(_translate("MainWindow", "Normalized Residuals Menu"))
        self.removeAirglow.setStatusTip(_translate("MainWindow", "Remove the current airglow from the COS data for the given line"))
        self.removeAirglow.setText(_translate("MainWindow", "Remove Airglow"))
        self.removalPlots.setStatusTip(_translate("MainWindow", "Reopen the plots generated with \'Remove Airglow\'"))
        self.removalPlots.setText(_translate("MainWindow", "View Airglow Removal Plots"))
        self.openBootstrap.setStatusTip(_translate("MainWindow", "Open the residual resampling circular block bootstrap menu"))
        self.openBootstrap.setText(_translate("MainWindow", "Bootstrapping Menu"))
        self.saveData.setStatusTip(_translate("MainWindow", "Save the current recovered spectrum to a file"))
        self.saveData.setText(_translate("MainWindow", "Save Recovered Spectrum"))
        self.fitScale.setStatusTip(_translate("MainWindow", "Move the slider to scale the entire fit"))
        self.fitscaleLabel.setStatusTip(_translate("MainWindow", "The best fit can be scaled"))
        self.fitscaleLabel.setText(_translate("MainWindow", "Best Fit\n"
" Scale"))
        self.fitscaleInput.setToolTip(_translate("MainWindow", "Press \'Enter\' when done"))
        self.fitscaleInput.setStatusTip(_translate("MainWindow", "Enter the best fit scale value"))
        self.scaleLabel.setStatusTip(_translate("MainWindow", "Input value for the airglow scale"))
        self.scaleLabel.setText(_translate("MainWindow", "Airglow\n"
"Scale"))
        self.scaleInput.setToolTip(_translate("MainWindow", "Press \'Enter\' when done"))
        self.scaleInput.setStatusTip(_translate("MainWindow", "Input the airglow scale value"))
        self.airScale.setStatusTip(_translate("MainWindow", "Move the slider to change the airglow scale input value"))
        
class bootstrapUi(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(350, 275)
        Dialog.setMinimumSize(QtCore.QSize(350, 275))
        Dialog.setMaximumSize(QtCore.QSize(350, 275))
        self.gridLayout_2 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.windowLabel = QtWidgets.QLabel(parent=Dialog)
        self.windowLabel.setMaximumSize(QtCore.QSize(16777215, 50))
        self.windowLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.windowLabel.setObjectName("windowLabel")
        self.gridLayout_2.addWidget(self.windowLabel, 0, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.lengthLabel = QtWidgets.QLabel(parent=Dialog)
        self.lengthLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lengthLabel.setObjectName("lengthLabel")
        self.gridLayout.addWidget(self.lengthLabel, 2, 0, 1, 1)
        self.lengthNumber = QtWidgets.QLabel(parent=Dialog)
        self.lengthNumber.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lengthNumber.setObjectName("lengthNumber")
        self.gridLayout.addWidget(self.lengthNumber, 2, 1, 1, 1)
        self.sampleLabel = QtWidgets.QLabel(parent=Dialog)
        self.sampleLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.sampleLabel.setObjectName("sampleLabel")
        self.gridLayout.addWidget(self.sampleLabel, 1, 0, 1, 1)
        self.sampleNumber = QtWidgets.QLabel(parent=Dialog)
        self.sampleNumber.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.sampleNumber.setObjectName("sampleNumber")
        self.gridLayout.addWidget(self.sampleNumber, 1, 1, 1, 1)
        self.paramNumber = QtWidgets.QLabel(parent=Dialog)
        self.paramNumber.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.paramNumber.setObjectName("paramNumber")
        self.gridLayout.addWidget(self.paramNumber, 0, 1, 1, 1)
        self.paramLabel = QtWidgets.QLabel(parent=Dialog)
        self.paramLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.paramLabel.setObjectName("paramLabel")
        self.gridLayout.addWidget(self.paramLabel, 0, 0, 1, 1)
        self.blockLabel = QtWidgets.QLabel(parent=Dialog)
        self.blockLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.blockLabel.setObjectName("blockLabel")
        self.gridLayout.addWidget(self.blockLabel, 3, 0, 1, 1)
        self.blockNumber = QtWidgets.QLabel(parent=Dialog)
        self.blockNumber.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.blockNumber.setObjectName("blockNumber")
        self.gridLayout.addWidget(self.blockNumber, 3, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 1, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setText("")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.bootTracker = QtWidgets.QProgressBar(parent=Dialog)
        self.bootTracker.setMaximum(1000)
        self.bootTracker.setProperty("value", 0)
        self.bootTracker.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.bootTracker.setObjectName("bootTracker")
        self.verticalLayout.addWidget(self.bootTracker)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.waitLabel = QtWidgets.QLabel(parent=Dialog)
        self.waitLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.waitLabel.setObjectName("waitLabel")
        self.horizontalLayout.addWidget(self.waitLabel)
        self.timeLabel = QtWidgets.QLabel(parent=Dialog)
        self.timeLabel.setObjectName("timeLabel")
        self.horizontalLayout.addWidget(self.timeLabel)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout_2.addLayout(self.verticalLayout, 3, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.runButton = QtWidgets.QPushButton(parent=Dialog)
        self.runButton.setObjectName("runButton")
        self.horizontalLayout_2.addWidget(self.runButton)
        self.cancelButton = QtWidgets.QPushButton(parent=Dialog)
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout_2.addWidget(self.cancelButton)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 4, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Bootstrapping Menu"))
        self.windowLabel.setText(_translate("Dialog", "Residual Resampling Circular Block Bootstrap (RRCBB)"))
        self.lengthLabel.setToolTip(_translate("Dialog", "The optimal block length for this dataset"))
        self.lengthLabel.setText(_translate("Dialog", "Optimal Block Length:"))
        self.lengthNumber.setText(_translate("Dialog", "N/A"))
        self.sampleLabel.setToolTip(_translate("Dialog", "The number of bootstrapped profiles to be generated"))
        self.sampleLabel.setText(_translate("Dialog", "Number of Bootstrap Samples:"))
        self.sampleNumber.setText(_translate("Dialog", "N/A"))
        self.paramNumber.setText(_translate("Dialog", "N/A"))
        self.paramLabel.setToolTip(_translate("Dialog", "The number of free parameters which will be bootstrapped"))
        self.paramLabel.setText(_translate("Dialog", "Number of Parameters: "))
        self.blockLabel.setToolTip(_translate("Dialog", "The number of blocks to be used"))
        self.blockLabel.setText(_translate("Dialog", "Number of Blocks:"))
        self.blockNumber.setText(_translate("Dialog", "N/A"))
        self.bootTracker.setToolTip(_translate("Dialog", "Progress bar for the bootstrapping process"))
        self.bootTracker.setFormat(_translate("Dialog", "%p%"))
        self.waitLabel.setToolTip(_translate("Dialog", "Estimated wait time until completion, in minutes"))
        self.waitLabel.setText(_translate("Dialog", "Estimated Wait Time: "))
        self.timeLabel.setText(_translate("Dialog", "N/A"))
        self.runButton.setToolTip(_translate("Dialog", "Run the RRCBB (NOTE: if GUI appears to freeze, RRCBB is likely still running in the background!)"))
        self.runButton.setText(_translate("Dialog", "Run RRCBB"))
        self.cancelButton.setToolTip(_translate("Dialog", "Do not run the RRCBB, return to the main window"))
        self.cancelButton.setText(_translate("Dialog", "Cancel"))
        
class missingUi(object):
    def setupUi(self, missingDialog):
        missingDialog.setObjectName("missingDialog")
        missingDialog.resize(333, 196)
        self.gridLayout_3 = QtWidgets.QGridLayout(missingDialog)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.inputName = QtWidgets.QLineEdit(parent=missingDialog)
        self.inputName.setObjectName("inputName")
        self.gridLayout.addWidget(self.inputName, 1, 1, 1, 1)
        self.labelName = QtWidgets.QLabel(parent=missingDialog)
        self.labelName.setObjectName("labelName")
        self.gridLayout.addWidget(self.labelName, 1, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.applyValues = QtWidgets.QPushButton(parent=missingDialog)
        self.applyValues.setMaximumSize(QtCore.QSize(210, 16777215))
        self.applyValues.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.applyValues.setWhatsThis("")
        self.applyValues.setObjectName("applyValues")
        self.horizontalLayout_3.addWidget(self.applyValues)
        self.gridLayout.addLayout(self.horizontalLayout_3, 6, 0, 1, 2)
        self.labelLP = QtWidgets.QLabel(parent=missingDialog)
        self.labelLP.setWhatsThis("")
        self.labelLP.setObjectName("labelLP")
        self.gridLayout.addWidget(self.labelLP, 2, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.life1 = QtWidgets.QRadioButton(parent=missingDialog)
        self.life1.setWhatsThis("")
        self.life1.setObjectName("life1")
        self.lifeGroup = QtWidgets.QButtonGroup(missingDialog)
        self.lifeGroup.setObjectName("lifeGroup")
        self.lifeGroup.addButton(self.life1)
        self.horizontalLayout.addWidget(self.life1)
        self.life2 = QtWidgets.QRadioButton(parent=missingDialog)
        self.life2.setWhatsThis("")
        self.life2.setObjectName("life2")
        self.lifeGroup.addButton(self.life2)
        self.horizontalLayout.addWidget(self.life2)
        self.life3 = QtWidgets.QRadioButton(parent=missingDialog)
        self.life3.setWhatsThis("")
        self.life3.setObjectName("life3")
        self.lifeGroup.addButton(self.life3)
        self.horizontalLayout.addWidget(self.life3)
        self.life4 = QtWidgets.QRadioButton(parent=missingDialog)
        self.life4.setWhatsThis("")
        self.life4.setObjectName("life4")
        self.lifeGroup.addButton(self.life4)
        self.horizontalLayout.addWidget(self.life4)
        self.life5 = QtWidgets.QRadioButton(parent=missingDialog)
        self.life5.setObjectName("life5")
        self.lifeGroup.addButton(self.life5)
        self.horizontalLayout.addWidget(self.life5)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 1, 1, 1)
        self.line = QtWidgets.QFrame(parent=missingDialog)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 4, 0, 1, 2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.cen1327 = QtWidgets.QCheckBox(parent=missingDialog)
        self.cen1327.setObjectName("cen1327")
        self.horizontalLayout_2.addWidget(self.cen1327)
        self.mDwarf = QtWidgets.QCheckBox(parent=missingDialog)
        self.mDwarf.setObjectName("mDwarf")
        self.horizontalLayout_2.addWidget(self.mDwarf)
        self.justA = QtWidgets.QCheckBox(parent=missingDialog)
        self.justA.setWhatsThis("")
        self.justA.setObjectName("justA")
        self.horizontalLayout_2.addWidget(self.justA)
        self.gridLayout.addLayout(self.horizontalLayout_2, 3, 0, 1, 2)
        self.displayInfo = QtWidgets.QLabel(parent=missingDialog)
        self.displayInfo.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.displayInfo.setFont(font)
        self.displayInfo.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.displayInfo.setObjectName("displayInfo")
        self.gridLayout.addWidget(self.displayInfo, 0, 0, 1, 2)
        self.gridLayout_3.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(missingDialog)
        QtCore.QMetaObject.connectSlotsByName(missingDialog)

    def retranslateUi(self, missingDialog):
        _translate = QtCore.QCoreApplication.translate
        missingDialog.setWindowTitle(_translate("missingDialog", "Missing Information"))
        self.inputName.setToolTip(_translate("missingDialog", "Type the name of the star here"))
        self.labelName.setText(_translate("missingDialog", "Star Name:"))
        self.applyValues.setToolTip(_translate("missingDialog", "Press after all information is provided"))
        self.applyValues.setText(_translate("missingDialog", "Apply"))
        self.labelLP.setToolTip(_translate("missingDialog", "The lifetime position used when this data was taken"))
        self.labelLP.setText(_translate("missingDialog", "Lifetime Position:"))
        self.life1.setText(_translate("missingDialog", "1"))
        self.life2.setText(_translate("missingDialog", "2"))
        self.life3.setText(_translate("missingDialog", "3"))
        self.life4.setText(_translate("missingDialog", "4"))
        self.life5.setText(_translate("missingDialog", "5"))
        self.cen1327.setToolTip(_translate("missingDialog", "Check if data was taken using Cenwave 1327"))
        self.cen1327.setText(_translate("missingDialog", "Cenwave 1327?"))
        self.mDwarf.setToolTip(_translate("missingDialog", "Check if the star is an M Type"))
        self.mDwarf.setText(_translate("missingDialog", "M Type?"))
        self.justA.setToolTip(_translate("missingDialog", "Check if data was taken using only Side A of the COS detector"))
        self.justA.setText(_translate("missingDialog", "Side A Only?"))
        self.displayInfo.setText(_translate("missingDialog", "Could Not Obtain the Following Information from the File\n"
"Please Fill In The Missing Information Below "))
        
class rangeUi(object):
    def setupUi(self, rangeDialog):
        rangeDialog.setObjectName("rangeDialog")
        rangeDialog.resize(380, 250)
        rangeDialog.setMinimumSize(QtCore.QSize(380, 250))
        rangeDialog.setMaximumSize(QtCore.QSize(380, 250))
        rangeDialog.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.gridLayout = QtWidgets.QGridLayout(rangeDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.minOI6 = QtWidgets.QLineEdit(parent=rangeDialog)
        self.minOI6.setStatusTip("")
        self.minOI6.setWhatsThis("")
        self.minOI6.setObjectName("minOI6")
        self.gridLayout.addWidget(self.minOI6, 3, 1, 1, 1)
        self.cancelRange = QtWidgets.QPushButton(parent=rangeDialog)
        self.cancelRange.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.cancelRange.setStatusTip("")
        self.cancelRange.setWhatsThis("")
        self.cancelRange.setObjectName("cancelRange")
        self.gridLayout.addWidget(self.cancelRange, 5, 3, 1, 1)
        self.rangeLabelOI5 = QtWidgets.QLabel(parent=rangeDialog)
        self.rangeLabelOI5.setStatusTip("")
        self.rangeLabelOI5.setWhatsThis("")
        self.rangeLabelOI5.setObjectName("rangeLabelOI5")
        self.gridLayout.addWidget(self.rangeLabelOI5, 2, 0, 1, 1)
        self.dashOI2 = QtWidgets.QLabel(parent=rangeDialog)
        self.dashOI2.setObjectName("dashOI2")
        self.gridLayout.addWidget(self.dashOI2, 1, 2, 1, 1)
        self.minOI2 = QtWidgets.QLineEdit(parent=rangeDialog)
        self.minOI2.setStatusTip("")
        self.minOI2.setWhatsThis("")
        self.minOI2.setObjectName("minOI2")
        self.gridLayout.addWidget(self.minOI2, 1, 1, 1, 1)
        self.angOI6 = QtWidgets.QLabel(parent=rangeDialog)
        self.angOI6.setObjectName("angOI6")
        self.gridLayout.addWidget(self.angOI6, 3, 4, 1, 1)
        self.rangeLabelOI6 = QtWidgets.QLabel(parent=rangeDialog)
        self.rangeLabelOI6.setStatusTip("")
        self.rangeLabelOI6.setWhatsThis("")
        self.rangeLabelOI6.setObjectName("rangeLabelOI6")
        self.gridLayout.addWidget(self.rangeLabelOI6, 3, 0, 1, 1)
        self.dashLyA = QtWidgets.QLabel(parent=rangeDialog)
        self.dashLyA.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.dashLyA.setObjectName("dashLyA")
        self.gridLayout.addWidget(self.dashLyA, 0, 2, 1, 1)
        self.rangeLabelLyA = QtWidgets.QLabel(parent=rangeDialog)
        self.rangeLabelLyA.setStatusTip("")
        self.rangeLabelLyA.setWhatsThis("")
        self.rangeLabelLyA.setObjectName("rangeLabelLyA")
        self.gridLayout.addWidget(self.rangeLabelLyA, 0, 0, 1, 1)
        self.dashOI5 = QtWidgets.QLabel(parent=rangeDialog)
        self.dashOI5.setObjectName("dashOI5")
        self.gridLayout.addWidget(self.dashOI5, 2, 2, 1, 1)
        self.minLyA = QtWidgets.QLineEdit(parent=rangeDialog)
        self.minLyA.setFocusPolicy(QtCore.Qt.FocusPolicy.StrongFocus)
        self.minLyA.setAcceptDrops(True)
        self.minLyA.setStatusTip("")
        self.minLyA.setWhatsThis("")
        self.minLyA.setObjectName("minLyA")
        self.gridLayout.addWidget(self.minLyA, 0, 1, 1, 1)
        self.angOI5 = QtWidgets.QLabel(parent=rangeDialog)
        self.angOI5.setObjectName("angOI5")
        self.gridLayout.addWidget(self.angOI5, 2, 4, 1, 1)
        self.maxOI2 = QtWidgets.QLineEdit(parent=rangeDialog)
        self.maxOI2.setStatusTip("")
        self.maxOI2.setWhatsThis("")
        self.maxOI2.setObjectName("maxOI2")
        self.gridLayout.addWidget(self.maxOI2, 1, 3, 1, 1)
        self.applyRange = QtWidgets.QPushButton(parent=rangeDialog)
        self.applyRange.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.applyRange.setStatusTip("")
        self.applyRange.setWhatsThis("")
        self.applyRange.setObjectName("applyRange")
        self.gridLayout.addWidget(self.applyRange, 5, 1, 1, 1)
        self.maxOI6 = QtWidgets.QLineEdit(parent=rangeDialog)
        self.maxOI6.setStatusTip("")
        self.maxOI6.setWhatsThis("")
        self.maxOI6.setObjectName("maxOI6")
        self.gridLayout.addWidget(self.maxOI6, 3, 3, 1, 1)
        self.angLyA = QtWidgets.QLabel(parent=rangeDialog)
        self.angLyA.setObjectName("angLyA")
        self.gridLayout.addWidget(self.angLyA, 0, 4, 1, 1)
        self.dashOI6 = QtWidgets.QLabel(parent=rangeDialog)
        self.dashOI6.setObjectName("dashOI6")
        self.gridLayout.addWidget(self.dashOI6, 3, 2, 1, 1)
        self.minOI5 = QtWidgets.QLineEdit(parent=rangeDialog)
        self.minOI5.setStatusTip("")
        self.minOI5.setWhatsThis("")
        self.minOI5.setObjectName("minOI5")
        self.gridLayout.addWidget(self.minOI5, 2, 1, 1, 1)
        self.maxLyA = QtWidgets.QLineEdit(parent=rangeDialog)
        self.maxLyA.setStatusTip("")
        self.maxLyA.setWhatsThis("")
        self.maxLyA.setObjectName("maxLyA")
        self.gridLayout.addWidget(self.maxLyA, 0, 3, 1, 1)
        self.rangeLabelOI2 = QtWidgets.QLabel(parent=rangeDialog)
        self.rangeLabelOI2.setStatusTip("")
        self.rangeLabelOI2.setWhatsThis("")
        self.rangeLabelOI2.setObjectName("rangeLabelOI2")
        self.gridLayout.addWidget(self.rangeLabelOI2, 1, 0, 1, 1)
        self.maxOI5 = QtWidgets.QLineEdit(parent=rangeDialog)
        self.maxOI5.setStatusTip("")
        self.maxOI5.setWhatsThis("")
        self.maxOI5.setObjectName("maxOI5")
        self.gridLayout.addWidget(self.maxOI5, 2, 3, 1, 1)
        self.angOI2 = QtWidgets.QLabel(parent=rangeDialog)
        self.angOI2.setObjectName("angOI2")
        self.gridLayout.addWidget(self.angOI2, 1, 4, 1, 1)

        self.retranslateUi(rangeDialog)
        QtCore.QMetaObject.connectSlotsByName(rangeDialog)
        rangeDialog.setTabOrder(self.minLyA, self.maxLyA)
        rangeDialog.setTabOrder(self.maxLyA, self.minOI2)
        rangeDialog.setTabOrder(self.minOI2, self.maxOI2)
        rangeDialog.setTabOrder(self.maxOI2, self.minOI5)
        rangeDialog.setTabOrder(self.minOI5, self.maxOI5)
        rangeDialog.setTabOrder(self.maxOI5, self.minOI6)
        rangeDialog.setTabOrder(self.minOI6, self.maxOI6)

    def retranslateUi(self, rangeDialog):
        _translate = QtCore.QCoreApplication.translate
        rangeDialog.setWindowTitle(_translate("rangeDialog", "Edit Ranges"))
        self.minOI6.setToolTip(_translate("rangeDialog", "OI 1306 Minimum"))
        self.cancelRange.setToolTip(_translate("rangeDialog", "Keep previous wavelength ranges"))
        self.cancelRange.setText(_translate("rangeDialog", "Cancel"))
        self.rangeLabelOI5.setToolTip(_translate("rangeDialog", "Wavelength range for OI 1305"))
        self.rangeLabelOI5.setText(_translate("rangeDialog", "OI 1305 Range:"))
        self.dashOI2.setText(_translate("rangeDialog", "     -     "))
        self.minOI2.setToolTip(_translate("rangeDialog", "OI 1302 Minimum"))
        self.angOI6.setText(_translate("rangeDialog", "Å"))
        self.rangeLabelOI6.setToolTip(_translate("rangeDialog", "Wavelength range for OI 1306"))
        self.rangeLabelOI6.setText(_translate("rangeDialog", "OI 1306 Range:"))
        self.dashLyA.setText(_translate("rangeDialog", "     -     "))
        self.rangeLabelLyA.setToolTip(_translate("rangeDialog", "Wavelength range for Lyman Alpha"))
        self.rangeLabelLyA.setText(_translate("rangeDialog", "      Lyα Range:"))
        self.dashOI5.setText(_translate("rangeDialog", "     -     "))
        self.minLyA.setToolTip(_translate("rangeDialog", "Lyα Minimum"))
        self.angOI5.setText(_translate("rangeDialog", "Å"))
        self.maxOI2.setToolTip(_translate("rangeDialog", "OI 1302 Maximum"))
        self.applyRange.setToolTip(_translate("rangeDialog", "Apply the changes made above"))
        self.applyRange.setText(_translate("rangeDialog", "Apply"))
        self.maxOI6.setToolTip(_translate("rangeDialog", "OI 1306 Maximum"))
        self.angLyA.setText(_translate("rangeDialog", "Å"))
        self.dashOI6.setText(_translate("rangeDialog", "     -     "))
        self.minOI5.setToolTip(_translate("rangeDialog", "OI 1305 Minimum"))
        self.maxLyA.setToolTip(_translate("rangeDialog", "Lyα Maximum"))
        self.rangeLabelOI2.setToolTip(_translate("rangeDialog", "Wavelength range for OI 1302"))
        self.rangeLabelOI2.setText(_translate("rangeDialog", "OI 1302 Range:"))
        self.maxOI5.setToolTip(_translate("rangeDialog", "OI 1305 Maximum"))
        self.angOI2.setText(_translate("rangeDialog", "Å"))
        
class recoveredUi(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(350, 150)
        Dialog.setMinimumSize(QtCore.QSize(350, 150))
        Dialog.setMaximumSize(QtCore.QSize(350, 150))
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.newButton = QtWidgets.QPushButton(parent=Dialog)
        self.newButton.setWhatsThis("")
        self.newButton.setObjectName("newButton")
        self.gridLayout.addWidget(self.newButton, 2, 0, 1, 1)
        self.cancelButton = QtWidgets.QPushButton(parent=Dialog)
        self.cancelButton.setWhatsThis("")
        self.cancelButton.setObjectName("cancelButton")
        self.gridLayout.addWidget(self.cancelButton, 2, 1, 1, 1)
        self.spectrumLabel = QtWidgets.QLabel(parent=Dialog)
        self.spectrumLabel.setMinimumSize(QtCore.QSize(315, 80))
        self.spectrumLabel.setMaximumSize(QtCore.QSize(16777215, 100))
        self.spectrumLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.spectrumLabel.setObjectName("spectrumLabel")
        self.gridLayout.addWidget(self.spectrumLabel, 1, 0, 1, 2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Airglow Already Removed"))
        self.newButton.setToolTip(_translate("Dialog", "Delete the current recovered spectrum and create a new one"))
        self.newButton.setText(_translate("Dialog", "Create New Spectrum"))
        self.cancelButton.setToolTip(_translate("Dialog", "Cancel the airglow removal for this line"))
        self.cancelButton.setText(_translate("Dialog", "Cancel"))
        self.spectrumLabel.setText(_translate("Dialog", "Airglow has already been removed from this line.\n"
" Do you want to create a new recovered spectrum\n"
" with the current airglow template removed?\n"
""))
        
class residualsUi(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(900, 600)
        MainWindow.setMinimumSize(QtCore.QSize(900, 600))
        MainWindow.setMaximumSize(QtCore.QSize(900, 600))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setMaximumSize(QtCore.QSize(120, 16777215))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.cutoffLabel = QtWidgets.QLabel(parent=self.widget)
        self.cutoffLabel.setMaximumSize(QtCore.QSize(120, 16777215))
        self.cutoffLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.cutoffLabel.setObjectName("cutoffLabel")
        self.verticalLayout.addWidget(self.cutoffLabel)
        self.cutoffInput = QtWidgets.QLineEdit(parent=self.widget)
        self.cutoffInput.setMaximumSize(QtCore.QSize(120, 16777215))
        self.cutoffInput.setObjectName("cutoffInput")
        self.verticalLayout.addWidget(self.cutoffInput)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.confirmCutoff = QtWidgets.QPushButton(parent=self.widget)
        self.confirmCutoff.setMaximumSize(QtCore.QSize(120, 25))
        self.confirmCutoff.setObjectName("confirmCutoff")
        self.verticalLayout.addWidget(self.confirmCutoff)
        self.cancelCutoff = QtWidgets.QPushButton(parent=self.widget)
        self.cancelCutoff.setMaximumSize(QtCore.QSize(120, 25))
        self.cancelCutoff.setObjectName("cancelCutoff")
        self.verticalLayout.addWidget(self.cancelCutoff)
        self.gridLayout.addWidget(self.widget, 0, 3, 1, 1)
        self.MplWidgetResid = MplWidget2(parent=self.centralwidget)
        self.MplWidgetResid.setMinimumSize(QtCore.QSize(0, 500))
        self.MplWidgetResid.setMaximumSize(QtCore.QSize(800, 500))
        self.MplWidgetResid.setObjectName("MplWidgetResid")
        self.gridLayout.addWidget(self.MplWidgetResid, 0, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 900, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Normalized Residuals Menu"))
        self.cutoffLabel.setStatusTip(_translate("MainWindow", "Points with a normalized residual above the cutoff will be masked out"))
        self.cutoffLabel.setText(_translate("MainWindow", "Enter Normalized\n"
" Residual Cutoff:"))
        self.cutoffInput.setToolTip(_translate("MainWindow", "Press \'Enter\' when done"))
        self.cutoffInput.setStatusTip(_translate("MainWindow", "Enter the residual cutoff here"))
        self.cutoffInput.setText(_translate("MainWindow", "inf"))
        self.confirmCutoff.setStatusTip(_translate("MainWindow", "Apply the residual cutoff and recalculate the best fit"))
        self.confirmCutoff.setText(_translate("MainWindow", "Apply"))
        self.cancelCutoff.setStatusTip(_translate("MainWindow", "Do not apply the residual cutoff, keep the current fit"))
        self.cancelCutoff.setText(_translate("MainWindow", "Cancel"))
        
class resultsUi(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(420, 625)
        Dialog.setMinimumSize(QtCore.QSize(420, 625))
        Dialog.setMaximumSize(QtCore.QSize(420, 625))
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.starfluxValue = QtWidgets.QLabel(parent=Dialog)
        self.starfluxValue.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.starfluxValue.setObjectName("starfluxValue")
        self.gridLayout.addWidget(self.starfluxValue, 26, 1, 1, 1)
        self.starfluxLabel = QtWidgets.QLabel(parent=Dialog)
        self.starfluxLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.starfluxLabel.setObjectName("starfluxLabel")
        self.gridLayout.addWidget(self.starfluxLabel, 26, 0, 1, 1)
        self.recovfluxLabel = QtWidgets.QLabel(parent=Dialog)
        self.recovfluxLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.recovfluxLabel.setObjectName("recovfluxLabel")
        self.gridLayout.addWidget(self.recovfluxLabel, 27, 0, 1, 1)
        self.line_3 = QtWidgets.QFrame(parent=Dialog)
        self.line_3.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout.addWidget(self.line_3, 19, 0, 1, 2)
        self.linecenLabel = QtWidgets.QLabel(parent=Dialog)
        self.linecenLabel.setWhatsThis("")
        self.linecenLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.linecenLabel.setObjectName("linecenLabel")
        self.gridLayout.addWidget(self.linecenLabel, 1, 0, 1, 1)
        self.coldensLabel = QtWidgets.QLabel(parent=Dialog)
        self.coldensLabel.setWhatsThis("")
        self.coldensLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.coldensLabel.setObjectName("coldensLabel")
        self.gridLayout.addWidget(self.coldensLabel, 12, 0, 1, 1)
        self.ismLabel = QtWidgets.QLabel(parent=Dialog)
        self.ismLabel.setWhatsThis("")
        self.ismLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.ismLabel.setObjectName("ismLabel")
        self.gridLayout.addWidget(self.ismLabel, 11, 0, 1, 2)
        self.line_2 = QtWidgets.QFrame(parent=Dialog)
        self.line_2.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 10, 0, 1, 2)
        self.starvradValue = QtWidgets.QLabel(parent=Dialog)
        self.starvradValue.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.starvradValue.setObjectName("starvradValue")
        self.gridLayout.addWidget(self.starvradValue, 2, 1, 1, 1)
        self.redchiValue = QtWidgets.QLabel(parent=Dialog)
        self.redchiValue.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.redchiValue.setObjectName("redchiValue")
        self.gridLayout.addWidget(self.redchiValue, 22, 1, 1, 1)
        self.ampValue = QtWidgets.QLabel(parent=Dialog)
        self.ampValue.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.ampValue.setObjectName("ampValue")
        self.gridLayout.addWidget(self.ampValue, 5, 1, 1, 1)
        self.coldensValue = QtWidgets.QLabel(parent=Dialog)
        self.coldensValue.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.coldensValue.setObjectName("coldensValue")
        self.gridLayout.addWidget(self.coldensValue, 12, 1, 1, 1)
        self.starvradLabel = QtWidgets.QLabel(parent=Dialog)
        self.starvradLabel.setWhatsThis("")
        self.starvradLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.starvradLabel.setObjectName("starvradLabel")
        self.gridLayout.addWidget(self.starvradLabel, 2, 0, 1, 1)
        self.lorentzValue = QtWidgets.QLabel(parent=Dialog)
        self.lorentzValue.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lorentzValue.setObjectName("lorentzValue")
        self.gridLayout.addWidget(self.lorentzValue, 4, 1, 1, 1)
        self.stellarLabel = QtWidgets.QLabel(parent=Dialog)
        self.stellarLabel.setWhatsThis("")
        self.stellarLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.stellarLabel.setObjectName("stellarLabel")
        self.gridLayout.addWidget(self.stellarLabel, 0, 0, 1, 2)
        self.ismvradLabel = QtWidgets.QLabel(parent=Dialog)
        self.ismvradLabel.setWhatsThis("")
        self.ismvradLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.ismvradLabel.setObjectName("ismvradLabel")
        self.gridLayout.addWidget(self.ismvradLabel, 13, 0, 1, 1)
        self.line = QtWidgets.QFrame(parent=Dialog)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 15, 0, 1, 2)
        self.lorentzLabel = QtWidgets.QLabel(parent=Dialog)
        self.lorentzLabel.setWhatsThis("")
        self.lorentzLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lorentzLabel.setObjectName("lorentzLabel")
        self.gridLayout.addWidget(self.lorentzLabel, 4, 0, 1, 1)
        self.gaussValue = QtWidgets.QLabel(parent=Dialog)
        self.gaussValue.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.gaussValue.setObjectName("gaussValue")
        self.gridLayout.addWidget(self.gaussValue, 3, 1, 1, 1)
        self.redchiLabel = QtWidgets.QLabel(parent=Dialog)
        self.redchiLabel.setWhatsThis("")
        self.redchiLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.redchiLabel.setObjectName("redchiLabel")
        self.gridLayout.addWidget(self.redchiLabel, 22, 0, 1, 1)
        self.gaussLabel = QtWidgets.QLabel(parent=Dialog)
        self.gaussLabel.setWhatsThis("")
        self.gaussLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.gaussLabel.setObjectName("gaussLabel")
        self.gridLayout.addWidget(self.gaussLabel, 3, 0, 1, 1)
        self.ampLabel = QtWidgets.QLabel(parent=Dialog)
        self.ampLabel.setWhatsThis("")
        self.ampLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.ampLabel.setObjectName("ampLabel")
        self.gridLayout.addWidget(self.ampLabel, 5, 0, 1, 1)
        self.linecenValue = QtWidgets.QLabel(parent=Dialog)
        self.linecenValue.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.linecenValue.setObjectName("linecenValue")
        self.gridLayout.addWidget(self.linecenValue, 1, 1, 1, 1)
        self.revwidthValue = QtWidgets.QLabel(parent=Dialog)
        self.revwidthValue.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.revwidthValue.setObjectName("revwidthValue")
        self.gridLayout.addWidget(self.revwidthValue, 8, 1, 1, 1)
        self.ismvradValue = QtWidgets.QLabel(parent=Dialog)
        self.ismvradValue.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.ismvradValue.setObjectName("ismvradValue")
        self.gridLayout.addWidget(self.ismvradValue, 13, 1, 1, 1)
        self.agscaleValue = QtWidgets.QLabel(parent=Dialog)
        self.agscaleValue.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.agscaleValue.setObjectName("agscaleValue")
        self.gridLayout.addWidget(self.agscaleValue, 18, 1, 1, 1)
        self.chiValue = QtWidgets.QLabel(parent=Dialog)
        self.chiValue.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.chiValue.setObjectName("chiValue")
        self.gridLayout.addWidget(self.chiValue, 21, 1, 1, 1)
        self.statsLabel = QtWidgets.QLabel(parent=Dialog)
        self.statsLabel.setWhatsThis("")
        self.statsLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.statsLabel.setObjectName("statsLabel")
        self.gridLayout.addWidget(self.statsLabel, 20, 0, 1, 2)
        self.agscaleLabel = QtWidgets.QLabel(parent=Dialog)
        self.agscaleLabel.setWhatsThis("")
        self.agscaleLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.agscaleLabel.setObjectName("agscaleLabel")
        self.gridLayout.addWidget(self.agscaleLabel, 18, 0, 1, 1)
        self.chiLabel = QtWidgets.QLabel(parent=Dialog)
        self.chiLabel.setWhatsThis("")
        self.chiLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.chiLabel.setObjectName("chiLabel")
        self.gridLayout.addWidget(self.chiLabel, 21, 0, 1, 1)
        self.agshiftValue = QtWidgets.QLabel(parent=Dialog)
        self.agshiftValue.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.agshiftValue.setObjectName("agshiftValue")
        self.gridLayout.addWidget(self.agshiftValue, 17, 1, 1, 1)
        self.revwidthLabel = QtWidgets.QLabel(parent=Dialog)
        self.revwidthLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.revwidthLabel.setObjectName("revwidthLabel")
        self.gridLayout.addWidget(self.revwidthLabel, 8, 0, 1, 1)
        self.revdepthValue = QtWidgets.QLabel(parent=Dialog)
        self.revdepthValue.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.revdepthValue.setObjectName("revdepthValue")
        self.gridLayout.addWidget(self.revdepthValue, 9, 1, 1, 1)
        self.airglowLabel = QtWidgets.QLabel(parent=Dialog)
        self.airglowLabel.setWhatsThis("")
        self.airglowLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.airglowLabel.setObjectName("airglowLabel")
        self.gridLayout.addWidget(self.airglowLabel, 16, 0, 1, 2)
        self.dopbValue = QtWidgets.QLabel(parent=Dialog)
        self.dopbValue.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.dopbValue.setObjectName("dopbValue")
        self.gridLayout.addWidget(self.dopbValue, 14, 1, 1, 1)
        self.bicValue = QtWidgets.QLabel(parent=Dialog)
        self.bicValue.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.bicValue.setObjectName("bicValue")
        self.gridLayout.addWidget(self.bicValue, 23, 1, 1, 1)
        self.agshiftLabel = QtWidgets.QLabel(parent=Dialog)
        self.agshiftLabel.setWhatsThis("")
        self.agshiftLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.agshiftLabel.setObjectName("agshiftLabel")
        self.gridLayout.addWidget(self.agshiftLabel, 17, 0, 1, 1)
        self.bicLabel = QtWidgets.QLabel(parent=Dialog)
        self.bicLabel.setWhatsThis("")
        self.bicLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.bicLabel.setObjectName("bicLabel")
        self.gridLayout.addWidget(self.bicLabel, 23, 0, 1, 1)
        self.dopbLabel = QtWidgets.QLabel(parent=Dialog)
        self.dopbLabel.setWhatsThis("")
        self.dopbLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.dopbLabel.setObjectName("dopbLabel")
        self.gridLayout.addWidget(self.dopbLabel, 14, 0, 1, 1)
        self.revdepthLabel = QtWidgets.QLabel(parent=Dialog)
        self.revdepthLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.revdepthLabel.setObjectName("revdepthLabel")
        self.gridLayout.addWidget(self.revdepthLabel, 9, 0, 1, 1)
        self.srLabel = QtWidgets.QLabel(parent=Dialog)
        self.srLabel.setMinimumSize(QtCore.QSize(380, 0))
        self.srLabel.setMaximumSize(QtCore.QSize(380, 16777215))
        self.srLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.srLabel.setObjectName("srLabel")
        self.gridLayout.addWidget(self.srLabel, 7, 0, 1, 2)
        self.stisfluxValue = QtWidgets.QLabel(parent=Dialog)
        self.stisfluxValue.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.stisfluxValue.setObjectName("stisfluxValue")
        self.gridLayout.addWidget(self.stisfluxValue, 28, 1, 1, 1)
        self.recovfluxValue = QtWidgets.QLabel(parent=Dialog)
        self.recovfluxValue.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.recovfluxValue.setObjectName("recovfluxValue")
        self.gridLayout.addWidget(self.recovfluxValue, 27, 1, 1, 1)
        self.stisfluxLabel = QtWidgets.QLabel(parent=Dialog)
        self.stisfluxLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.stisfluxLabel.setObjectName("stisfluxLabel")
        self.gridLayout.addWidget(self.stisfluxLabel, 28, 0, 1, 1)
        self.line_5 = QtWidgets.QFrame(parent=Dialog)
        self.line_5.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout.addWidget(self.line_5, 24, 0, 1, 2)
        self.fluxLabel = QtWidgets.QLabel(parent=Dialog)
        self.fluxLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.fluxLabel.setObjectName("fluxLabel")
        self.gridLayout.addWidget(self.fluxLabel, 25, 0, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem, 6, 0, 1, 2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Best Fit Results"))
        self.starfluxValue.setText(_translate("Dialog", "N/A"))
        self.starfluxLabel.setToolTip(_translate("Dialog", "Integrated flux of the (self reversed) stellar emission profile, in ergs per cm squared per second"))
        self.starfluxLabel.setText(_translate("Dialog", "Stellar Fit Profile (erg/cm^2/s):"))
        self.recovfluxLabel.setToolTip(_translate("Dialog", "Integrated flux of the recovered profile, in ergs per cm squared per second"))
        self.recovfluxLabel.setText(_translate("Dialog", "Recovered Profile (erg/cm^2/s):"))
        self.linecenLabel.setToolTip(_translate("Dialog", "The central wavelength of the selected line, in Angstroms. This value is always fixed"))
        self.linecenLabel.setText(_translate("Dialog", "Line Center (Å):"))
        self.coldensLabel.setToolTip(_translate("Dialog", "The order of magnitude of the ISM column density in the direction of the star, in inverse cm squared"))
        self.coldensLabel.setText(_translate("Dialog", "Column Density (10^x  cm^-2):"))
        self.ismLabel.setToolTip(_translate("Dialog", "Parameters used for creating the ISM attenuation profile"))
        self.ismLabel.setText(_translate("Dialog", "ISM Parameters"))
        self.starvradValue.setText(_translate("Dialog", "N/A"))
        self.redchiValue.setText(_translate("Dialog", "N/A"))
        self.ampValue.setText(_translate("Dialog", "N/A"))
        self.coldensValue.setText(_translate("Dialog", "N/A"))
        self.starvradLabel.setToolTip(_translate("Dialog", "The radial velocity of the star, in km/s"))
        self.starvradLabel.setText(_translate("Dialog", "Stellar Radial Velocity (km/s):"))
        self.lorentzValue.setText(_translate("Dialog", "N/A"))
        self.stellarLabel.setToolTip(_translate("Dialog", "Parameters used for creating the stellar profile"))
        self.stellarLabel.setText(_translate("Dialog", "Stellar Parameters"))
        self.ismvradLabel.setToolTip(_translate("Dialog", "The radial velocity of the ISM in the direction of the star, in km/s"))
        self.ismvradLabel.setText(_translate("Dialog", "ISM Radial Velocity (km/s):"))
        self.lorentzLabel.setToolTip(_translate("Dialog", "The Lorentzian FWHM of the Voigt stellar profile, in km/s"))
        self.lorentzLabel.setText(_translate("Dialog", "Lorentzian FWHM (km/s):"))
        self.gaussValue.setText(_translate("Dialog", "N/A"))
        self.redchiLabel.setToolTip(_translate("Dialog", "The reduced chi squared value of the fit"))
        self.redchiLabel.setText(_translate("Dialog", "Reduced Chi Squared:"))
        self.gaussLabel.setToolTip(_translate("Dialog", "The Gaussian FWHM of the Gaussian/Voigt stellar profile, in km/s"))
        self.gaussLabel.setText(_translate("Dialog", "Gaussian FWHM (km/s):"))
        self.ampLabel.setToolTip(_translate("Dialog", "The order of magnitude of the stellar profile\'s flux amplitude "))
        self.ampLabel.setText(_translate("Dialog", "Flux Amplitude (10^x):"))
        self.linecenValue.setText(_translate("Dialog", "N/A"))
        self.revwidthValue.setText(_translate("Dialog", "N/A"))
        self.ismvradValue.setText(_translate("Dialog", "N/A"))
        self.agscaleValue.setText(_translate("Dialog", "N/A"))
        self.chiValue.setText(_translate("Dialog", "N/A"))
        self.statsLabel.setToolTip(_translate("Dialog", "Statistics for evaluating goodness of fit"))
        self.statsLabel.setText(_translate("Dialog", "Fit Statistics"))
        self.agscaleLabel.setToolTip(_translate("Dialog", "The scale factor of the airglow template"))
        self.agscaleLabel.setText(_translate("Dialog", "Scale:"))
        self.chiLabel.setToolTip(_translate("Dialog", "The chi squared value of the fit"))
        self.chiLabel.setText(_translate("Dialog", "Chi Squared:"))
        self.agshiftValue.setText(_translate("Dialog", "N/A"))
        self.revwidthLabel.setToolTip(_translate("Dialog", "The self reversal FWHM, fixed at 0.47x the Gaussian FWHM"))
        self.revwidthLabel.setText(_translate("Dialog", "Self Reversal FWHM (km/s):"))
        self.revdepthValue.setText(_translate("Dialog", "N/A"))
        self.airglowLabel.setToolTip(_translate("Dialog", "Parameters used for placing the airglow template"))
        self.airglowLabel.setText(_translate("Dialog", "Airglow Parameters"))
        self.dopbValue.setText(_translate("Dialog", "N/A"))
        self.bicValue.setText(_translate("Dialog", "N/A"))
        self.agshiftLabel.setToolTip(_translate("Dialog", "The spectral shift of the airglow template, in Angstroms"))
        self.agshiftLabel.setText(_translate("Dialog", "Shift (Å):"))
        self.bicLabel.setToolTip(_translate("Dialog", "The BIC of the fit"))
        self.bicLabel.setText(_translate("Dialog", "Bayesian Info Criteria:"))
        self.dopbLabel.setToolTip(_translate("Dialog", "The doppler b parameter, in km/s. This value is degenerate with the column density so it remains fixed"))
        self.dopbLabel.setText(_translate("Dialog", "Doppler b Parameter (km/s):"))
        self.revdepthLabel.setToolTip(_translate("Dialog", "The self reversal depth, 0.5 for FGK Types, and 0.35 for M Types"))
        self.revdepthLabel.setText(_translate("Dialog", "Self Reversal Depth Fraction:"))
        self.srLabel.setToolTip(_translate("Dialog", "Parameters used for creating the self reversal profile"))
        self.srLabel.setText(_translate("Dialog", "Self Reversal Parameters"))
        self.stisfluxValue.setText(_translate("Dialog", "N/A"))
        self.recovfluxValue.setText(_translate("Dialog", "N/A"))
        self.stisfluxLabel.setToolTip(_translate("Dialog", "Integrated flux of the scaled STIS profile, in ergs per cm squared per second"))
        self.stisfluxLabel.setText(_translate("Dialog", "Scaled STIS Profile (erg/cm^2/s):"))
        self.fluxLabel.setToolTip(_translate("Dialog", "Various integrated fluxes"))
        self.fluxLabel.setText(_translate("Dialog", "Integrated Fluxes"))
        
class stisUi(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(929, 621)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.MplWidgetSTIS = MplWidget(parent=self.centralwidget)
        self.MplWidgetSTIS.setMinimumSize(QtCore.QSize(800, 500))
        self.MplWidgetSTIS.setMaximumSize(QtCore.QSize(800, 500))
        self.MplWidgetSTIS.setObjectName("MplWidgetSTIS")
        self.gridLayout.addWidget(self.MplWidgetSTIS, 3, 0, 1, 1)
        self.dialogLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.dialogLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.dialogLabel.setObjectName("dialogLabel")
        self.gridLayout.addWidget(self.dialogLabel, 0, 0, 1, 2)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.cosIntlabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.cosIntlabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.cosIntlabel.setObjectName("cosIntlabel")
        self.horizontalLayout_5.addWidget(self.cosIntlabel)
        self.cosIntvalue = QtWidgets.QLabel(parent=self.centralwidget)
        self.cosIntvalue.setText("")
        self.cosIntvalue.setObjectName("cosIntvalue")
        self.horizontalLayout_5.addWidget(self.cosIntvalue)
        self.stisIntlabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.stisIntlabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.stisIntlabel.setObjectName("stisIntlabel")
        self.horizontalLayout_5.addWidget(self.stisIntlabel)
        self.stisIntvalue = QtWidgets.QLabel(parent=self.centralwidget)
        self.stisIntvalue.setText("")
        self.stisIntvalue.setObjectName("stisIntvalue")
        self.horizontalLayout_5.addWidget(self.stisIntvalue)
        self.gridLayout.addLayout(self.horizontalLayout_5, 1, 0, 1, 1)
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setMaximumSize(QtCore.QSize(100, 500))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.sliderSTIS = QtWidgets.QSlider(parent=self.widget)
        self.sliderSTIS.setMaximum(1000)
        self.sliderSTIS.setPageStep(0)
        self.sliderSTIS.setProperty("value", 100)
        self.sliderSTIS.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.sliderSTIS.setObjectName("sliderSTIS")
        self.horizontalLayout.addWidget(self.sliderSTIS)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.labelSTIS = QtWidgets.QLabel(parent=self.widget)
        self.labelSTIS.setMinimumSize(QtCore.QSize(0, 0))
        self.labelSTIS.setMaximumSize(QtCore.QSize(100, 16777215))
        self.labelSTIS.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.labelSTIS.setObjectName("labelSTIS")
        self.verticalLayout.addWidget(self.labelSTIS)
        self.inputSTIS = QtWidgets.QLineEdit(parent=self.widget)
        self.inputSTIS.setMinimumSize(QtCore.QSize(0, 0))
        self.inputSTIS.setMaximumSize(QtCore.QSize(100, 16777215))
        self.inputSTIS.setObjectName("inputSTIS")
        self.verticalLayout.addWidget(self.inputSTIS)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.gridLayout.addWidget(self.widget, 3, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 929, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.sliderSTIS, self.inputSTIS)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "STIS Comparison"))
        self.dialogLabel.setStatusTip(_translate("MainWindow", "Displayed using the current airglow input values and radial velocities"))
        self.dialogLabel.setText(_translate("MainWindow", "Displaying the Recovered Spectrum using Current Fit Parameters"))
        self.cosIntlabel.setStatusTip(_translate("MainWindow", "Integrated flux of the recovered COS profile"))
        self.cosIntlabel.setText(_translate("MainWindow", "COS Integrated Flux:"))
        self.stisIntlabel.setStatusTip(_translate("MainWindow", "Integrated flux of the scaled STIS profile"))
        self.stisIntlabel.setText(_translate("MainWindow", "STIS Integrated Flux:"))
        self.sliderSTIS.setStatusTip(_translate("MainWindow", "Move the slider to change the STIS scale factor"))
        self.labelSTIS.setStatusTip(_translate("MainWindow", "The scale factor of the STIS data "))
        self.labelSTIS.setText(_translate("MainWindow", "STIS\n"
"Scale"))
        self.inputSTIS.setToolTip(_translate("MainWindow", "Press \'Enter\' when done"))
        self.inputSTIS.setStatusTip(_translate("MainWindow", "Enter the STIS scale factor here"))
        
class MplWidget(QtWidgets.QWidget):
    def __init__(self,parent=None):
        super().__init__()
        layout=QtWidgets.QVBoxLayout()
        self.setLayout(layout)
        self.canvas=FigureCanvas(Figure())
        layout.addWidget(self.canvas)
        self.canvas.axes=self.canvas.figure.add_subplot(111)
        
class MplWidget2(QtWidgets.QWidget):
    def __init__(self,parent=None):
        super().__init__()
        layout=QtWidgets.QVBoxLayout()
        self.setLayout(layout)
        self.canvas=FigureCanvas(Figure())
        layout.addWidget(self.canvas)
        self.canvas.axes1=self.canvas.figure.add_subplot(211)
        self.canvas.axes2=self.canvas.figure.add_subplot(212,sharex=self.canvas.axes1)
        


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = mainUi()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
